# Generated by Django 4.0.2 on 2022-04-15 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=24)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('credito_limite', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('credito_disponivel', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fechamento_fatura', models.IntegerField(max_length=2)),
                ('vencimento_fatura', models.IntegerField(max_length=2)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=24)),
                ('slug', models.SlugField(max_length=28)),
                ('cor', models.CharField(max_length=16)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=24)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_referente', models.DateField()),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.categoria')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_created=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('banco_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.banco')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.usuario')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
            },
        ),
        migrations.AddField(
            model_name='banco',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.usuario'),
        ),
    ]
