# Generated by Django 4.0.2 on 2022-04-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0002_alter_banco_criado_em_alter_categoria_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='gasto_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.gasto'),
        ),
    ]
