# Generated by Django 4.0.2 on 2022-02-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0003_alter_gastos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(),
        ),
    ]
