# Generated by Django 4.0.2 on 2022-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0003_remove_lancamento_gasto_fk_lancamento_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='ano',
            field=models.CharField(default='2022', max_length=4),
            preserve_default=False,
        ),
    ]
