# Generated by Django 4.0.2 on 2022-02-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0004_alter_gastos_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastos',
            old_name='data',
            new_name='data_referente',
        ),
    ]
