# Generated by Django 4.0.2 on 2022-04-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0004_remove_lancamento_gasto_fk_lancamento_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='lancamento_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_gestao.lancamento'),
            preserve_default=False,
        ),
    ]
