# Generated by Django 4.0.2 on 2022-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0006_alter_banco_fechamento_fatura_alter_banco_usuario_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#530D1E', max_length=16),
        ),
    ]
