# Generated by Django 4.0.2 on 2022-03-03 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gestao', '0006_categorias_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=24)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fechamento_fatura', models.DateField()),
                ('vencimento_fatura', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('limite_usado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mes_referente', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.bancos')),
            ],
        ),
        migrations.RenameField(
            model_name='gastos',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='gastos',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='gastos',
            name='valor',
        ),
        migrations.CreateModel(
            name='GastoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.faturas')),
                ('gasto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao.gastos')),
            ],
        ),
    ]
