# Generated by Django 4.0.2 on 2022-03-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0007_bancos_faturas_rename_categoria_gastos_categoria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bancos',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.RenameField(
            model_name='faturas',
            old_name='banco',
            new_name='banco_id',
        ),
    ]
