# Generated by Django 4.0.2 on 2022-04-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0007_alter_categoria_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#FC7B3C', max_length=16),
        ),
    ]
