# Generated by Django 4.0.2 on 2022-03-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0008_rename_usuario_bancos_usuario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastos',
            old_name='user_id',
            new_name='usuario_id',
        ),
    ]
