# Generated by Django 4.0.2 on 2022-03-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao', '0009_rename_user_id_gastos_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturas',
            name='limite_total',
        ),
        migrations.AddField(
            model_name='bancos',
            name='credito_disponivel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='bancos',
            name='credito_limite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='faturas',
            name='fechada',
            field=models.BooleanField(default=False),
        ),
    ]
