# Generated by Django 4.0.2 on 2022-03-08 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_gestao', '0010_remove_faturas_limite_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancos',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to=settings.AUTH_USER_MODEL),
        ),
    ]
